/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_robot_seabreeze_serial_SerialPort */

#ifndef _Included_com_robot_seabreeze_serial_SerialPort
#define _Included_com_robot_seabreeze_serial_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_robot_seabreeze_serial_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_robot_seabreeze_serial_SerialPort_open
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_robot_seabreeze_serial_SerialPort
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_robot_seabreeze_serial_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
